version: '3.3'

services:
    idempotencybundle_php:
        image: dh.rinsvent.ru/php8dev
        container_name: idempotencybundle_php
        volumes:
            - ./:/app
        environment:
            USE_COMPOSER_SCRIPTS: 0
            PHP_IDE_CONFIG: "serverName=idempotencybundle_php"
        depends_on:
            - idempotencybundle_redis
    idempotencybundle_redis:
        image: dh.rinsvent.ru/redis
        container_name: idempotencybundle_redis
        volumes:
            - ../idempotencybundle_data/redis:/data
        command: redis-server --requirepass password123

networks:
    default:
        external:
            name: full-project
